services:
  app:
    build: .
    container_name: acao-app
    restart: unless-stopped
    ports:
      - "${NODE_PORT:-3000}:3000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_URI=${MONGODB_URI:-mongodb://mongo:27017/acao}
    env_file: .env
    depends_on:
      - mongo
    networks:
      - bot-network

  mongo:
    container_name: acao-mongo
    image: mongo:latest
    restart: always
    ports:
      - "${MONGO_PORT:-27017}:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - bot-network

volumes:
  mongodb_data:

networks:
  bot-network:
